# -*- coding: utf-8 -*-
"""attack_all_classifiers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aEDb_JO0gxNxpwFpOaTdMSlvhS3MLzNe
"""

import os
import subprocess

def main():
    base_dir = "../experiments/attacks"

    # Remove and recreate the base directory
    if os.path.exists(base_dir):
        os.system(f"rm -rf {base_dir}")
    os.makedirs(base_dir)

    dataset_names = ["age", "age_short", "age_tinkoff", "rosbank"]
    target_classifiers = ["gru_with_amounts", "lstm_with_amounts", "cnn_with_amounts"]
    substitute_classifiers = ["gru_with_amounts", "lstm_with_amounts", "cnn_with_amounts"]

    for dataset_name in dataset_names:
        dataset_path = os.path.join(base_dir, dataset_name)
        os.makedirs(dataset_path, exist_ok=True)

        for targ_clf in target_classifiers:
            targ_path = os.path.join(dataset_path, f"targ_{targ_clf}")
            os.makedirs(targ_path, exist_ok=True)

            for subst_clf in substitute_classifiers:
                subst_path = os.path.join(targ_path, f"subst_{subst_clf}")
                os.makedirs(subst_path, exist_ok=True)

                # Run the bash script with subprocess
                subprocess.run(["bash", "scripts/local/attack.sh", subst_clf, targ_clf, "500", dataset_name])

if __name__ == "__main__":
    main()